ckp_dirname: ckp
device: cuda:0
extensions: []
fc1Dims: 1024
fc2Dims: 512
keys_from_agent:
- action_range
- action_dtype
- num_actions
- obs_shape
- obs_range
- obs_dtype
- seed
- experiment_folder
lr: 0.001
mem_dirname: mem